[LoadTest] Revamp load test suite
pokt-network/poktroll pull request #1002
Opened 2024-12-11 16:59 UTC by red-0ne

## Summary

This pull request includes several updates to the load-testing configuration and test files, as well as improvements to the relay stress test suite. The most important changes include updating funding account addresses, modifying gateway configurations, and refactoring various test functions for better accuracy.

## Type of change

Select one or more from the following:

- [ ] New feature, functionality or library
- [ ] Consensus breaking; add the `consensus-breaking` label if so. See #791 for details
- [x] Bug fix
- [ ] Code health or cleanup
- [ ] Documentation
- [ ] Other (specify)

## Testing

- [x] **Unit Tests**: `make go_develop_and_test`
- [x] **LocalNet E2E Tests**: `make test_e2e`
- [ ] **DevNet E2E Tests**: Add the `devnet-test-e2e` label to the PR.

## Sanity Checklist

- [x] I have tested my changes using the available tooling
- [ ] I have commented my code
- [x] I have performed a self-review of my own code; both comments & source code
- [ ] I create and reference any new tickets, if applicable
- [ ] I have left TODOs throughout the codebase, if applicable

2024-12-11 20:16 UTC, Olshansk commented
@red-0ne Lmk if you need me to take a look at this as well.

2024-12-20 21:34 UTC, Olshansk requested changes
@red-0ne Partial review.

This is great work but `load-testing/tests/relays_stress_helpers_test.go` is really hard to review right now with lots of big inline functions.

Do you mind doing a self passthrough and finding ways to make it a bit more readable & maintainable for others?

2024-12-20 21:34 UTC, Olshansk commented on load-testing/tests/relays_stress_helpers_test.go
> +		func(ctx context.Context, block client.Block) {
NIT: Can you assign this to a locally scope function so the `.ForEach` is easier to read?

2024-12-20 21:34 UTC, Olshansk commented on load-testing/tests/relays_stress_helpers_test.go
> +	amountToSpend := s.relayRatePerApp * s.relayCoinAmountCost * currentTestDuration * blockDuration
```suggestion
	relayCostDuringTestPOKT := s.relayRatePerApp * s.relayCoinAmountCost * currentTestDuration * blockDuration
```

2024-12-20 21:34 UTC, Olshansk commented on load-testing/tests/relays_stress_helpers_test.go
> +	appFundingAmount := math.Max(amountToSpend, s.appParams.MinStake.Amount.Int64()*2)
Move the comment starting with `Multiply by 2` above so it's above this line instead.

2024-12-20 21:34 UTC, Olshansk commented on load-testing/tests/relays_stress_helpers_test.go
> +		gwURL = gwURL + "/"
Can we just call it `gatewayURL` without the shortening?

2024-12-20 21:34 UTC, Olshansk commented on load-testing/tests/relays_stress_helpers_test.go
> +		req.Header.Add("X-App-Address", appAddr)
1. TODO_TECHDEBT to remove `x-`
2. #PUC why we need this

2024-12-20 21:34 UTC, Olshansk commented on load-testing/tests/relays_stress_helpers_test.go
> +	}(s.gatewayUrls[gateway.address], application.address, relayPayload)
What if you do something like:

```go
inlineFunc := func(...) {..}
gatewayURL := s.gatewayUrls[...]
go inlineFunc(gatewayURL, ...)
```

You'll need better names, but it'll be easier to maintain.,

2025-01-03 15:48 UTC, red-0ne commented
> @red-0ne Partial review.
> 
> This is great work but `load-testing/tests/relays_stress_helpers_test.go` is really hard to review right now with lots of big inline functions.
> 
> Do you mind doing a self passthrough and finding ways to make it a bit more readable & maintainable for others?

It is indeed very hard to follow, we have a TODO_TECHDEBT where we'll have to address this particular issue:

![image](https://github.com/user-attachments/assets/ab590269-33a7-4918-b7b2-7f68133b87ef)

Will create an issue and prioritize accordingly.

2025-01-03 15:57 UTC, red-0ne commented on load-testing/tests/relays_stress.feature
> +    # And "0" slashing events are observed
The load test should not exercise over servicing or slashing but rather always assert that none of them happen given a well functioning RelayMiner.

Additionally, in order to "force" the RelayMiner to have this behavior; we'll have to implement the functionality or set up the right environment to do so which I think would be in the scope of the E2E tests.

2025-01-03 23:50 UTC, Olshansk requested changes

2025-01-03 23:50 UTC, Olshansk commented on load-testing/tests/relays_stress_helpers_test.go
> +func (s *relaysSuite) setupEventListeners(pocketNode string) {
s/pocketNode/rpcNode?

2025-01-03 23:50 UTC, Olshansk commented on load-testing/tests/relays_stress_helpers_test.go
> +		// Query the block results endpoint for each observed block to get the tx and block events.
```suggestion
		// Query the block results endpoint for each observed block to get the tx and block events.
		// Ref: https://docs.cometbft.com/main/rpc/#/Info/block_results
```

2025-01-03 23:50 UTC, Olshansk commented on load-testing/tests/relays_stress_helpers_test.go
> +		events := make([]types.Event, 0, len(blockResults.TxsResults)+len(blockResults.FinalizeBlockEvents))
```suggestion
		numEvents := len(blockResults.TxsResults)+len(blockResults.FinalizeBlockEvents)
		events := make([]types.Event, 0, numEvents)
```

2025-01-03 23:50 UTC, Olshansk commented on load-testing/tests/relays_stress_helpers_test.go
> +		for _, txResult := range blockResults.TxsResults {
```suggestion
		// Flatten all tx result events and block event results into one slice
		for _, txResult := range blockResults.TxsResults {
```

2025-01-03 23:50 UTC, Olshansk commented on load-testing/tests/relays_stress_helpers_test.go
> +	relayCostDuringTestUPOKT := s.relayRatePerApp * s.relayCoinAmountCost * currentTestDuration * blockDuration
```suggestion
	// Compute the cost of all relays throughout the test duration
	totalRelayCostDuringTestUPOKT := s.relayRatePerApp * s.relayCoinAmountCost * currentTestDuration * blockDuration
```

2025-01-03 23:50 UTC, Olshansk commented on load-testing/tests/relays_stress_helpers_test.go
> +	txBuilder.SetTimeoutHeight(uint64(s.latestBlock.Height() + 2))
#PUC why this is +2

2025-01-03 23:50 UTC, Olshansk commented on load-testing/tests/relays_stress_helpers_test.go
> +		gatewayURL = gatewayURL + "/"
1. #PUC why we need to add "/"
2. Should we not check if there's a trailing / first? Maybe the std string library has something for it

2025-01-03 23:50 UTC, Olshansk commented on load-testing/tests/relays_stress_helpers_test.go
> +			s.failedRelays.Add(1)
1. Do we count successful relays anywhere?  If not, could be good for telemetry, printing & debugging later.
2. What do you think of doing a print statement every N (e.g. 100) relays like:

e.g. Sent: X relays; Success: Y; Failed: Z

2025-01-03 23:50 UTC, Olshansk commented on load-testing/tests/relays_stress_helpers_test.go
> +		return
log a warning?

2025-01-03 23:50 UTC, Olshansk commented on load-testing/tests/relays_stress_helpers_test.go
> +	deadline := time.Now().Add(time.Second * time.Duration(blockDuration+1))
NITs:

1. Should we rename `blockDuration` to `blockDurationSec`?
2. #PUC why +1

2025-01-03 23:50 UTC, Olshansk commented on load-testing/tests/relays_stress_helpers_test.go
> +			// Skip non-relevant events.
#PUC why `transfer` is the only relevant event

2025-01-03 23:50 UTC, Olshansk commented on load-testing/tests/relays_stress_helpers_test.go
> +// allActorsFunded checks if all the expected actors are funded.
```suggestion
// allActorsFunded checks if all the expected actors are funded.
// An error is returned if at least one of the expected actors was not funded.
```

2025-01-03 23:50 UTC, Olshansk commented on load-testing/tests/relays_stress_helpers_test.go
> +		s.logAndAbortTest("actors not funded")
```suggestion
		s.logAndAbortTest("at least one actor was not funded successfully")
```

2025-01-03 23:50 UTC, Olshansk commented on load-testing/tests/relays_stress_helpers_test.go
> +	deadline := time.Now().Add(time.Second * time.Duration(blockDuration+1))
Ditto

2025-01-03 23:50 UTC, Olshansk commented on load-testing/tests/relays_stress_helpers_test.go
> +		if allActorsStaked(actors, stakedActors) {
```suggestion
		// We can cancel exit this scope once all expected actors were successfully staked
		// before the deadline was reached.
		if allActorsStaked(actors, stakedActors) {
```

2025-01-03 23:50 UTC, Olshansk commented on load-testing/tests/relays_stress_helpers_test.go
> +// allActorsStaked checks if all the expected actors are staked.
```suggestion
// allActorsStaked checks if all the expected actors are staked.
// An error is returned if at least one of the expected actors was not staked.
```

2025-01-03 23:50 UTC, Olshansk commented on load-testing/tests/relays_stress_helpers_test.go
> +		s.logAndAbortTest("actors not staked")
```suggestion
		s.logAndAbortTest("at least one actor was not staked successfully")
```

2025-01-03 23:50 UTC, Olshansk commented on load-testing/tests/relays_stress_test.go
> +	// Setup the event listener for on-chain events to check and assert on transactions
s/on-chain/onchain

https://x.com/olshansky/status/1869115777800180217

Ditto everywhere else (e.g. line 330 below) but I won't leave any more comments.

Please do a find-all "on-chain"

2025-01-03 23:50 UTC, Olshansk commented on load-testing/tests/relays_stress_test.go
> +	stakedActors := append(suppliers, gateways...)
Trying to be consistent with "funded" above.

```suggestion
	stakedActors := append(stakedSuppliers, stakedGateways...)
```

2025-01-03 23:50 UTC, Olshansk commented on load-testing/tests/relays_stress_test.go
> +	s.ensureDelegatedApps(s.ctx, applications, gateways)
Ditto. consider adding a prefix

2025-01-03 23:50 UTC, Olshansk commented on load-testing/tests/relays_stress_helpers_test.go
> +// WaitAll waits for all the provided functions to complete.
Nicely done!

2025-01-03 23:50 UTC, Olshansk commented on load-testing/tests/relays_stress_helpers_test.go
> +func abciEventsToTypedEvents(ctx context.Context, abciEventObs observable.Observable[[]types.Event]) observable.Observable[[]proto.Message] {
OPTIONAL: What do you think of moving this into `poktroll/testutil/events/filter.go`?

2025-01-03 23:50 UTC, Olshansk commented on load-testing/tests/relays_stress_helpers_test.go
> +func (s *relaysSuite) WaitAll(waitFuncs ...func()) {
I noticed this doesn't use `s` at all. 

Can we move this into TestUtil?

2025-01-03 23:50 UTC, Olshansk commented on load-testing/tests/relays_stress_single_supplier.feature
> +    # And there is as many reimbursement requests as the number of settled claims
```suggestion
    # And there are as many reimbursement requests as the number of settled claims
```

2025-01-03 23:50 UTC, Olshansk commented on load-testing/tests/relays_stress_single_supplier.feature
> +    # And the actors onchain balances are as expected
Note to our selves: revisit some more interesting test cases here.

2025-01-03 23:50 UTC, Olshansk commented on load-testing/tests/relays_stress_test.go
> +	failedRelays atomic.Uint64
Per my other comment, considering counting successes as well.

2025-01-03 23:50 UTC, Olshansk commented on load-testing/tests/relays_stress_helpers_test.go
> +	appParams, err := appQueryclient.GetParams(s.ctx)
Why do all the other params need casting but this one doesn't?

2025-01-03 23:50 UTC, Olshansk commented on load-testing/tests/relays_stress_helpers_test.go
> +	var clientConn *grpc.ClientConn
Why is querying tokenomic params differen than proof and app params?

2025-01-06 18:26 UTC, red-0ne commented on load-testing/tests/relays_stress_helpers_test.go
> +func (s *relaysSuite) WaitAll(waitFuncs ...func()) {
Good catch!

2025-01-06 19:00 UTC, red-0ne commented on load-testing/tests/relays_stress_helpers_test.go
> +	appParams, err := appQueryclient.GetParams(s.ctx)
The `proofParams` need casting because its querier returns an interface [1]; which was added to avoid dependency cycles.

[1] https://github.com/pokt-network/poktroll/blob/main/pkg/client/interface.go#L335

2025-01-06 20:13 UTC, red-0ne commented on load-testing/tests/relays_stress_helpers_test.go
> +	var clientConn *grpc.ClientConn
The reason we're using the auto-generated query client is that we don't have the need to implement a tokenomics client querier for now since offchain packages don't need it (yet).

Added a `TODO_TECHDEBT` to use the tokenomics querier once implemented.

2025-01-07 04:40 UTC, red-0ne commented on load-testing/tests/relays_stress_test.go
> +	// Setup the event listener for on-chain events to check and assert on transactions
Replaced all the `on-chain/off-chain` occurrences with `onchain/offchain` but seemed too much changes for this already big PR.

Addressed them #1020

2025-01-09 18:01 UTC, Olshansk approved these changes
Just a few minor NITs but lets get it in afterwards!

2025-01-10 21:58 UTC, red-0ne commented on load-testing/tests/relays_stress_test.go
> +	// Initialize the on-chain settlement events listener.
Fixed on PR #1020

2025-01-10 22:02 UTC, red-0ne commented on testutil/delays/waitall.go
> +}
Neat!

2025-01-10 23:36 UTC, merged