[RelayMiner] Use gas for claim and proof txs
pokt-network/poktroll pull request #1018
Opened 2024-12-20 20:51 UTC by red-0ne

## Summary

This pull request includes several changes to the `pkg/client` package, focusing on adding gas limit and gas price parameters to transaction signing and broadcasting functions, as well as making related updates in tests and configurations.

It also updates the `BroadcastTx` method in `pkg/client/tx/context.go` to use `BroadcastTxSync` instead of `BroadcastTxAsync` for better error handling during the check-tx ABCI operation.

Minor Fix:
* Changed the URL in `makefiles/relay.mk` to include a trailing slash.

## Issue

![image](https://github.com/user-attachments/assets/535e99b3-621b-46bd-a335-49e167c50cba)

## Type of change

Select one or more from the following:

- [ ] New feature, functionality or library
- [ ] Consensus breaking; add the `consensus-breaking` label if so. See #791 for details
- [x] Bug fix
- [ ] Code health or cleanup
- [ ] Documentation
- [ ] Other (specify)

## Testing

- [ ] **Documentation**: `make docusaurus_start`; only needed if you make doc changes
- [x] **Unit Tests**: `make go_develop_and_test`
- [x] **LocalNet E2E Tests**: `make test_e2e`
- [ ] **DevNet E2E Tests**: Add the `devnet-test-e2e` label to the PR.

## Sanity Checklist

- [x] I have tested my changes using the available tooling
- [x] I have commented my code
- [x] I have performed a self-review of my own code; both comments & source code
- [ ] I create and reference any new tickets, if applicable
- [x] I have left TODOs throughout the codebase, if applicable

2024-12-20 21:36 UTC, Olshansk approved these changes
Thank you for handling this so quickly!

2024-12-20 21:36 UTC, Olshansk commented on pkg/client/interface.go
> +		gasPrice int64,
```suggestion
		gasLimit, gasPrice int64,
```

2024-12-20 21:36 UTC, Olshansk commented on pkg/client/supplier/client.go
> +	// TODO_TECHDEBT: Gas limit and price should have their dedicated configuration entry.
```suggestion
	// TODO_TECHDEBT(@okdas): Gas limit and price should have their dedicated configuration entry.
```

2024-12-20 21:36 UTC, Olshansk commented on pkg/client/tx/client.go
> +	gasPrice int64,
Ditto

2024-12-20 22:12 UTC, okdas commented
```json
{"level":"info","message":"Starting relay miner..."}
{"level":"info","message":"starting relayer sessions manager"}
{"level":"info","endpoint":"localhost:6060","message":"starting a pprof endpoint"}
{"level":"info","endpoint":":9090","message":"serving metrics"}
{"level":"info","message":"starting relayer proxy"}
{"level":"info","server host":"0.0.0.0:8545","message":"starting relay proxy server"}
{"level":"info","message":"starting ring cache"}
{"level":"info","session_end_height":34020,"claim_window_open_height":34022,"message":"waiting & blocking until the earliest claim commit height offset seed block height"}
{"level":"info","session_end_height":34020,"claim_window_open_height":34022,"claim_window_open_block_hash":"cd1ef990487790b33d764349f0ef61e30dfd835d4383228209d5e140584fe6f5","message":"observed earliest claim commit height offset seed block height"}
{"level":"info","session_end_height":34020,"claim_window_open_height":34022,"claim_window_open_block_hash":"cd1ef990487790b33d764349f0ef61e30dfd835d4383228209d5e140584fe6f5","earliest_claim_commit_height":34022,"message":"waiting & blocking until the earliest claim commit height for this supplier"}
{"level":"info","session_end_height":34020,"claim_window_open_height":34022,"claim_window_open_block_hash":"cd1ef990487790b33d764349f0ef61e30dfd835d4383228209d5e140584fe6f5","earliest_claim_commit_height":34022,"message":"observed earliest claim commit height"}
{"level":"error","error":"out of gas in location: ReadFlat; gasWanted: 100000, gasUsed: 100905: out of gas: error during ABCI check tx","message":"failed to create claims"}
{"level":"error","error":"out of gas in location: ReadFlat; gasWanted: 100000, gasUsed: 100905: out of gas: error during ABCI check tx"}

```

Seems like we need to bump the fees if we're not going to make it configurable at the moment.

2024-12-20 22:14 UTC, okdas commented on pkg/client/supplier/client.go
> +	gasLimit = 100000
```suggestion
	gasLimit = 300000
```
Let's make it larger and see if it'll be enough.

2025-01-03 00:16 UTC, okdas commented on pkg/client/tx/client.go
> +	gasLimit, simErr := txnClient.txCtx.GetSimulatedTxGas(ctx, txnClient.signingKeyName, msgs...)
This is very cool

2025-01-03 10:16 UTC, bryanchriswhite approved these changes
Very cool - thanks @red-0ne! :rocket:

2025-01-03 10:16 UTC, bryanchriswhite commented on pkg/client/tx/context.go
> +// GetSimulatedTxGas calculates the gas for the given messages using the simulation mode.
:heart_on_fire: :rocket:

2025-01-03 10:16 UTC, bryanchriswhite commented on pkg/client/tx/context.go
> +	// the check-tx ABCI operation, otherwise errors would be returned.
:+1:

2025-01-03 10:16 UTC, bryanchriswhite commented on pkg/relayer/cmd/cmd.go
> +	cmd.Flags().Float64(cosmosflags.FlagGasAdjustment, 1.5, "The adjustment factor to be multiplied by the estimate returned by the tx simulation; if the gas limit is set manually this flag is ignored")
```suggestion
	cmd.Flags().Float64(cosmosflags.FlagGasAdjustment, 1.5, "The adjustment factor to be multiplied by the gas estimate returned by the tx simulation; if the gas limit is set manually this flag is ignored")
```

2025-01-03 22:58 UTC, Olshansk requested changes
Looks great! Requesting changes just because I know this is still an active WIP.

2025-01-03 22:58 UTC, Olshansk commented on pkg/client/tx/context.go
> +}
This func is CLEAN!

2025-01-03 22:58 UTC, Olshansk commented on pkg/client/tx/context.go
> +	// BroadcastTxSync is used to capture any transaction error that occurs during
Great comment

2025-01-03 22:58 UTC, Olshansk commented on pkg/client/tx/client.go
> +	// Coin multiplication prevents doing it using a zero value.
I don't understand this comment. Can you #PUC?

2025-01-03 22:58 UTC, Olshansk commented on pkg/client/tx/client.go
> +	if gasLimit > 0 {
If gasLimit is zero, does that mean there's no limit?

If so, #PUC

2025-01-03 22:58 UTC, Olshansk commented on pkg/client/tx/client.go
> +		gasLimitDec := math.LegacyNewDec(int64(gasLimit))
Why aren't we using `math.NewDec` here?

2025-01-03 22:58 UTC, Olshansk commented on pkg/client/tx/client.go
> +		feeCoins, changeCoins := feeAmountDec.TruncateDecimal()
s/changeCoins/remainderCoins?

2025-01-03 22:58 UTC, Olshansk commented on pkg/client/tx/client.go
> +		for i, coin := range feeCoins {
```suggestion
		for i, feeCoin := range feeCoins {
```

2025-01-03 22:58 UTC, Olshansk commented on pkg/client/tx/client.go
> +			if !changeCoins[i].IsZero() {
Should we also ensure `changeCoins` is < 1?

2025-01-03 22:58 UTC, Olshansk commented on pkg/client/tx/client.go
> +	gasPrices cosmostypes.DecCoins
```suggestion
	// gas is a special unit type in the cosmos sdk; https://docs.cosmos.network/main/learn/beginner/gas-fees
	gasPrices cosmostypes.DecCoins
```

2025-01-03 22:58 UTC, Olshansk commented on pkg/client/tx/client.go
> +	gasLimit, simErr := txnClient.txCtx.GetSimulatedTxGas(ctx, txnClient.signingKeyName, msgs...)
🆒

2025-01-03 22:58 UTC, Olshansk commented on pkg/relayer/cmd/cmd.go
> +	cmd.Flags().String(cosmosflags.FlagGasPrices, "1upokt", "Set the gas prices in upokt")
```suggestion
	cmd.Flags().String(cosmosflags.FlagGasPrices, "1upokt", "Set the gas unit price in upokt")
```

2025-01-03 22:58 UTC, Olshansk commented on pkg/client/tx/client.go
> +		if !changeCoins.IsZero() {
Should we not check/enforce that this is less than 1?

2025-01-03 22:58 UTC, Olshansk commented on pkg/deps/config/suppliers.go
> +		}
1. If it's something else, can we log it?
2. WHen would something else show up here?

2025-01-03 23:22 UTC, red-0ne commented on pkg/client/tx/client.go
> +		gasLimitDec := math.LegacyNewDec(int64(gasLimit))
There's no `NewDec`, even `DecCoins` use `LegacyDec` :face_with_diagonal_mouth:

2025-01-06 22:24 UTC, Olshansk commented on pkg/client/tx/client.go
> +	// Ensure that any decimal remainder is added to the corresponding coin as a
Thank you for the comment and new code structure!

2025-01-06 22:25 UTC, Olshansk approved these changes
Awesome work, ty @red-0ne!

2025-01-07 05:08 UTC, merged