[Sessions] chore: Use depinject for sessions mgr construction
pokt-network/poktroll pull request #175
Opened 2023-11-09 22:16 UTC by red-0ne

## Summary

### Human Summary

Use depinject to construct `relayerSessionsManager`.

### AI Summary

reviewpad:summary

## Type of change

Select one or more:

- [ ] New feature, functionality or library
- [ ] Bug fix
- [x] Code health or cleanup
- [ ] Documentation
- [ ] Other (specify)

## Testing

- [ ] **Run all unit tests**: `make go_develop_and_test`
- [ ] **Verify Localnet manually**: See the instructions [here](TODO: add link to instructions)

## Sanity Checklist

- [ ] I have tested my changes using the available tooling
- [x] I have performed a self-review of my own code
- [x] I have commented my code, updated documentation and left TODOs throughout the codebase

2023-11-09 22:25 UTC, Olshansk requested changes

2023-11-09 22:25 UTC, Olshansk commented on pkg/relayer/session/errors.go
> +	ErrUndefinedStoresDirectory     = sdkerrors.Register(codespace, 5, "undefined stores directory")
This goes a long way when we hit real issues

```suggestion
	ErrSessionTreeUndefinedStoresDirectory      = sdkerrors.Register(codespace, 5, "directory undefined for where to key-value stores should be saved on disk")
```

2023-11-09 22:25 UTC, Olshansk commented on pkg/relayer/session/session.go
> +func (rp *relayerSessionsManager) validateConfig() error {
```suggestion
// TODO_TEST: Add unit tests to validate these configurations
func (rp *relayerSessionsManager) validateConfig() error {
```

2023-11-09 22:33 UTC, bryanchriswhite commented on pkg/relayer/session/options.go
> +// WithStoresDirectory sets the path on disk where KVStore data files are created.
Is it worth trying to articulate what those files entail (e.g. session SMSTs, etc.)?

2023-11-09 22:35 UTC, bryanchriswhite approved these changes
Left a couple of comments but otherwise G2G! :rocket: 

Preemptively approving.

2023-11-10 00:06 UTC, Olshansk approved these changes

2023-11-10 00:38 UTC, merged