[Docs] Load Test #1 - Plan
pokt-network/poktroll pull request #286
Opened 2023-12-20 02:40 UTC by Olshansk

## Summary

Documentation for the goals of the first load test.

### Human Summary

### AI Summary

reviewpad:summary

## Issue

- #229 

## Type of change

Select one or more:

- [ ] New feature, functionality or library
- [ ] Bug fix
- [ ] Code health or cleanup
- [x] Documentation
- [ ] Other (specify)

2024-01-04 19:25 UTC, red-0ne reviewed
Awesome plan! Eager to contribute to it.

Left a couple of comments but nothing blocking.

Implicitly approving and let other reviewers hit the approve button :)

2024-01-04 19:25 UTC, red-0ne commented on docusaurus/docs/infrastructure/testing/load_test_1.md
> +5. `Uncover` potential bugs or bottlenecks in both on-chain & off-chain code
We should also mention `potential concurrency issues`

2024-01-04 19:25 UTC, red-0ne commented on docusaurus/docs/infrastructure/testing/load_test_1.md
> +- `Request Processing` - Signature generation, request marshaling / unmarshaling, etc…
Slow `Supplier` replies could increase the pending relays at the `AppGate` level (RAM)

2024-01-04 19:39 UTC, h5law requested changes
Looks good, had a lot of trouble with the diagram left some suggestions there. Overall nice plan LFG!

2024-01-04 19:39 UTC, h5law commented on docusaurus/docs/infrastructure/testing/load_test_1.md
> +- `Relay Proxies` Ingress/egress of relays could add
Could add what?

2024-01-04 19:39 UTC, h5law commented on docusaurus/docs/infrastructure/testing/load_test_1.md
> +- `SMT` - The `SMT` is one of the most important parts of the end-to-end flow which has impact on `RAM`, `CPU` & `disk`
> The `SMT` is one of the most important parts of the end-to-end flow

Hehe <3

2024-01-04 19:39 UTC, h5law commented on docusaurus/docs/infrastructure/testing/load_test_1.md
> +    classDef blueColor fill:#0000FF;
```suggestion
    classDef blueColor fill:#75A8E6;
```
To me this was pink

2024-01-04 19:39 UTC, h5law commented on docusaurus/docs/infrastructure/testing/load_test_1.md
> +    classDef purpleColor fill:#800080;
```suggestion
    classDef purpleColor fill:#B160E3;
```
Hopefully this makes the text more readable

2024-01-04 19:39 UTC, h5law commented on docusaurus/docs/infrastructure/testing/load_test_1.md
> +- A script/tool to generate N requests per second
```suggestion
- A script/tool to generate $N$ requests per second
```

2024-01-05 12:46 UTC, red-0ne approved these changes
LGTM

2024-01-05 20:34 UTC, merged