[Testing, Tooling] refactor: in-memory network usage
pokt-network/poktroll pull request #307
Opened 2024-01-09 13:04 UTC by bryanchriswhite

## Summary

### Human Summary

Refactors usage of in-memory network in tests to utilize updated in-memory network testutils.

## Issue

- #141 
- #263
- #264
- #265 
- #289
- #290 
- :point_right: THIS PR :point_left: 
- #266 
- #250

## Type of change

Select one or more:

- [ ] New feature, functionality or library
- [ ] Bug fix
- [x] Code health or cleanup
- [ ] Documentation
- [ ] Other (specify)

## Testing

- [ ] **Run all unit tests**: `make go_develop_and_test`
- [ ] **Run E2E tests locally**: `make test_e2e`
- [ ] **Run E2E tests on DevNet**: Add the `devnet-test-e2e` label to the PR. This is VERY expensive, only do it after all the reviews are complete.

## Sanity Checklist

- [x] I have tested my changes using the available tooling
- [x] I have performed a self-review of my own code
- [x] I have commented my code, updated documentation and left TODOs throughout the codebase

2024-01-11 15:36 UTC, Olshansk requested changes
A few small comments. 

Let's merge with main, resolve/ignore the comments, run e2e tests and get this in!

2024-01-11 15:36 UTC, Olshansk commented on x/application/client/cli/tx_delegate_to_gateway_test.go
> +			appAddress:     appBech32,
I think we should one of `appAddr` or `appAddrBech32` to make the variable name more semantically clear.

2024-01-11 15:36 UTC, Olshansk commented on x/gateway/client/cli/tx_stake_gateway_test.go
> +	memnet := gatewaynet.NewInMemoryNetworkWithGateways(
Really like seeing this pattern everywhere.

2024-01-12 11:55 UTC, bryanchriswhite commented on testutil/network/basenet/accounts.go
> +	// Create a supplier on-chain account.
Will #PUC, this DOES NOT have anything to do with getting a public key on-chain. That only happens when a tx signed by this new account is received by the network (as commented elsewhere).

2024-01-12 15:23 UTC, bryanchriswhite commented on testutil/testclient/localnet.go
> -	cmd.InitSDKConfig()
It was causing issues:
![image](https://github.com/pokt-network/poktroll/assets/600733/21a9f501-1caf-4278-9f6d-ff9bb3a03697)

We need to be careful when where and how (i.e. `init` functions or not) we call this function as (AFAIK) there is currently no way to check whether it has already been called.

2024-04-02 11:42 UTC, bryanchriswhite commented
Closing, superseded by #412 & #417.

2024-04-02 11:42 UTC, closed without merging