[WIP] Docs
pokt-network/poktroll pull request #364
Opened 2024-02-06 00:59 UTC by Olshansk

## Summary

### Human Summary

 
### AI Summary

reviewpad:summary

## Issue

- #{ISSUE_NUMBER}

## Type of change

Select one or more:

- [ ] New feature, functionality or library
- [ ] Bug fix
- [ ] Code health or cleanup
- [ ] Documentation
- [ ] Other (specify)

## Testing

- [ ] **Run all unit tests**: `make go_develop_and_test`
- [ ] **Run E2E tests locally**: `make test_e2e`
- [ ] **Run E2E tests on DevNet**: Add the `devnet-test-e2e` label to the PR. This is VERY expensive, only do it after all the reviews are complete.

## Sanity Checklist

- [ ] I have tested my changes using the available tooling
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, updated documentation and left TODOs throughout the codebase

2024-02-14 05:54 UTC, red-0ne requested changes

2024-02-14 05:54 UTC, red-0ne commented on docusaurus/docs/actors/application.md
> +The on-chain for an `Application` can be found at [application.proto](./../../../proto/pocket/application/application.proto).
```suggestion
The on-chain representation of an `Application` can be found at [application.proto](./../../../proto/pocket/application/application.proto).
```

This makes me ask myself: "on-chain what?"

2024-02-14 05:54 UTC, red-0ne commented on docusaurus/docs/actors/gateway.md
> +The on-chain for an `Gateway` can be found at [gateway.proto](./../../../proto/pocket/gateway/gateway.proto).
Same, "on-chain what?"

2024-02-14 05:54 UTC, red-0ne commented on docusaurus/docs/actors/gateway.md
> +The on-chain for an `Gateway` can be found at [gateway.proto](./../../../proto/pocket/gateway/gateway.proto).
```suggestion
The on-chain for a `Gateway` can be found at [gateway.proto](./../../../proto/pocket/gateway/gateway.proto).
```

2024-02-14 05:54 UTC, red-0ne commented on docusaurus/docs/actors/relay_miner.md
> +An `RelayMiner` is responsible for for relaying requests between a client dApp
I think you wanted to say: Relaying requests between the `AppGate Server` and the `Service`

2024-02-14 05:54 UTC, red-0ne commented on docusaurus/docs/actors/relay_miner.md
> +A `Gateway` operator or a sovereign `Application` interested in accessing Pocket
This paragraph should talk about the `Supplier` interested in proposing `Services`

2024-02-14 05:54 UTC, red-0ne commented on docusaurus/docs/actors/relay_miner.md
> +Configurations to stake an `AppGate Server` can be found [relayminer_config.md](../configs/relayminer_config.md).
This should talk about configuration for operating a `RelayMiner`.

2024-02-14 05:54 UTC, red-0ne commented on docusaurus/docs/actors/relay_miner.md
> +All of the operations needed to start and operate an `AppGate Server` can be viewed by running:
```suggestion
All of the operations needed to start and operate a `RelayMiner` can be viewed by running:
```

2024-02-14 05:54 UTC, red-0ne commented on docusaurus/docs/actors/appgate_server.md
> +implements the same functionality.
Add a link referring to `POKTRollSDK`

2024-02-14 05:54 UTC, red-0ne commented on docusaurus/docs/actors/appgate_server.md
> +A `Gateway` operator or a sovereign `Application` interested in accessing Pocket
What do you think about having `Gateway`, `Application` and `Supplier` mentions as links to their respective pages?

2024-02-14 05:54 UTC, red-0ne commented on docusaurus/docs/actors/gateway.md
> +requests on behalf of an `Application`.
What about making the word `Application` a link to `docs/actors/application.md`

2024-02-14 05:54 UTC, red-0ne commented on docusaurus/docs/actors/supplier.md
> +All of the write (i.e. tx) based operations for the `Application` actor can be
```suggestion
All of the write (i.e. tx) based operations for the `Supplier` actor can be
```

2024-02-14 05:54 UTC, red-0ne commented on docusaurus/docs/actors/gateway.md
> +All of the write (i.e. tx) based operations for the `Application` actor can be
```suggestion
All of the write (i.e. tx) based operations for the `Gateway` actor can be
```

2024-02-15 01:43 UTC, red-0ne commented
@Olshansk I addressed the change requests in 0591dcb7b755f517c2d8c2bb0550bec3ad01a252

PTAL and make modification if/where needed.

2024-02-15 01:43 UTC, red-0ne approved these changes

2024-02-16 20:50 UTC, merged

2024-02-16 21:22 UTC, Olshansk commented
@red-0ne FYI: https://github.com/pokt-network/poktroll/commit/5a0981da72eed32763fd57fe8f40867f3d5e2a82