[Migration Review - DO NOT MERGE] Gateway module
pokt-network/poktroll pull request #374
Opened 2024-02-08 12:34 UTC by red-0ne

## Summary

### Human Summary

Gateway module migration based off of migration/base.

This does not include CLI nor its config

## Issue

- #240 

## Type of change

Select one or more:

- [ ] New feature, functionality or library
- [ ] Bug fix
- [x] Code health or cleanup
- [ ] Documentation
- [ ] Other (specify)

## Testing

- [ ] **Run all unit tests**: `make go_develop_and_test`
- [ ] **Run E2E tests locally**: `make test_e2e`
- [ ] **Run E2E tests on DevNet**: Add the `devnet-test-e2e` label to the PR. This is VERY expensive, only do it after all the reviews are complete.

## Sanity Checklist

- [ ] I have tested my changes using the available tooling
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, updated documentation and left TODOs throughout the codebase

2024-02-13 00:03 UTC, Olshansk requested changes

2024-02-13 22:28 UTC, red-0ne commented on Makefile
> +	# go generate ./x/application/types/
Each module migration is uncommenting its own mock generation. So when they everything is merged they'll be all uncommented.

2024-02-13 22:33 UTC, red-0ne commented on x/gateway/module/config/gateway_config_reader.go
> +package config
Checked, there's none that refers to them.

2024-02-13 22:37 UTC, red-0ne commented on x/gateway/module/genesis_test.go
> +package gateway_test
Good catch! They seem to serve the same purpose. We had them previously on `x/gateway/types/genesis_test.go` but now they seems to belong to `x/gateway/module/genesis_test.go`

2024-02-13 22:52 UTC, red-0ne commented on x/gateway/module/autocli.go
> +func (am AppModule) AutoCLIOptions() *autocliv1.ModuleOptions {
Currently `autocli` is not used to generate or to handle CLI commands. As of my understanding, we will wire it to our commands when it'll be possible to handle configuration files.

cc @bryanchriswhite

2024-02-13 23:41 UTC, red-0ne commented
@Olshansk, I addressed most of the change requests and left a couple of them with comments. PTAL.

2024-02-14 04:28 UTC, Olshansk approved these changes
Reviewed the changes and LGTM.

APproving for reference but DO NOT MERGE

2024-02-15 08:31 UTC, bryanchriswhite commented
@red-0ne please add `x/gateway/types.go`:

```
package types

// This file is in place to declare the package for dynamically generated protobufs
```

2024-02-22 00:42 UTC, closed without merging