[Proof] add proof submission integration tests
pokt-network/poktroll pull request #417
Opened 2024-03-07 11:54 UTC by bryanchriswhite

## Summary

### Human Summary

Adds integration tests exercising submit proof message handling.

### AI Summary

reviewpad:summary

## Issue

- #403 

## Type of change

Select one or more:

- [ ] New feature, functionality or library
- [ ] Bug fix
- [x] Code health or cleanup
- [ ] Documentation
- [ ] Other (specify)

## Testing

- [ ] **Run all unit tests**: `make go_develop_and_test`
- [ ] **Run E2E tests locally**: `make test_e2e`
- [ ] **Run E2E tests on DevNet**: Add the `devnet-test-e2e` label to the PR. This is VERY expensive, only do it after all the reviews are complete.

## Sanity Checklist

- [ ] I have tested my changes using the available tooling
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, updated documentation and left TODOs throughout the codebase

2024-03-12 17:30 UTC, h5law approved these changes
Nothing stands out to me, love the coverage :shipit:

2024-03-12 17:30 UTC, h5law commented on testutil/keeper/proof.go
>  // TODO_CONSIDERATION: can we remove the bank keeper as a dependency of the proof keeper?
For these comments I think by default the account and bank keeper are automatically added, if not used remove them - if it breaks add them back but I am 99.99% sure this is just an ignite thing.

2024-03-12 17:30 UTC, h5law commented on x/proof/keeper/msg_server_submit_proof_test.go
> +	// TODO_TECHDEBT: add a test case such that we can distinguish between early
```suggestion
	
	// TODO_TECHDEBT: add a test case such that we can distinguish between early
```

2024-03-12 18:42 UTC, bryanchriswhite commented on x/proof/keeper/msg_server_submit_proof_test.go
> +	// Ensure a valid relay response signature.
```suggestion
	// Ensure valid relay request and response signatures.
```

2024-03-12 18:46 UTC, bryanchriswhite commented on x/proof/keeper/msg_server_submit_proof_test.go
> +func newFilledSessionTree(
I neglected to add godoc comments to all these helpers. :facepalm:

2024-03-20 04:01 UTC, Olshansk requested changes
I made it to `desc: "relay request metadata is nil",` in the `proof_test` file and will continue tomorrow.

Overall, these are probably the most readable tests I've ever seen and are really set a great precedence and example. Awesome work @bryanchriswhite!

2024-03-21 23:31 UTC, Olshansk requested changes
@bryanchriswhite Finally finished reviewing this. 

Again, I think this is really high quality work but bear with my comments.

1. In some places I left short comments that require an investigation.
2. In some places I left comments that need to be addressed in different places.
3. Reviewing tests (as good as they are) isn't fun and difficult cognitive work, so I did my best but am sure I missed a bunch of stuff.

2024-03-21 23:31 UTC, Olshansk commented on x/proof/keeper/msg_server_submit_proof_test.go
> +					"error deserializing ring signature: %s",
Do we have unit tests where the relay signature is formatted correctly but comes from the incorrect signer?

2024-03-21 23:31 UTC, Olshansk commented on x/proof/keeper/msg_server_submit_proof_test.go
> +				// Advance the block height such that no hydration errors can occur when
I think we need to #PUC. I don't fully understand what this comment is explaining/

WHy would session start height < block height cause an issue?

2024-03-21 23:31 UTC, Olshansk commented on x/proof/keeper/msg_server_submit_proof_test.go
> +					"session headers session start heights mismatch; expected: %d, got: %d",
What assumption are we making about the numBlocksPerSession in this unit test?

2024-03-21 23:31 UTC, Olshansk commented on x/proof/keeper/msg_server_submit_proof_test.go
> +				// Create a valid claim.
Isn't this invalid because of the incorrect merkle root?

2024-03-21 23:31 UTC, Olshansk commented on x/proof/keeper/msg_server_submit_proof_test.go
> +			desc: "merkle proof must validate claimed merkle root",
Can you update this? Seems like "Valid proof cannot validate claim with invalid root".

2024-03-21 23:31 UTC, Olshansk commented on x/proof/keeper/msg_server_submit_proof_test.go
> +				t.Skip("this test case reduces to either the 'claim must exist for proof message' or 'proof session ID must match on-chain session ID cases")
This is a neat idea.

2024-03-21 23:31 UTC, Olshansk commented on x/proof/keeper/msg_server_submit_proof_test.go
> +			require.Lenf(t, proofs, 0, "expected 0 proofs, got %d", len(proofs))
Is it 0 because we don't have any tests for successful proofs? #PUC

2024-03-21 23:31 UTC, Olshansk commented on x/proof/keeper/msg_server_submit_proof_test.go
> +
```suggestion
```

2024-03-21 23:31 UTC, Olshansk commented on x/proof/keeper/msg_server_submit_proof_test.go
> +	supplierAddr string,
OPTIONAL NIT: Reminder that we could do `supplierKeyUid, supplierAddr string`

2024-03-21 23:31 UTC, Olshansk commented on x/proof/keeper/msg_server_submit_proof_test.go
> +	// TODO(@Red0ne) add a comment explaining why we have to do this.
```suggestion
	// TODO_DOCUMENT(@Red0ne): Update comment & documentation explaining why we have to do this.
	// Consider adding some centralized helpers for this anywhere where we do `+ GetSessionGracePeriod`
```

2024-03-21 23:31 UTC, Olshansk commented on x/proof/keeper/msg_server_submit_proof_test.go
> +	// Set the current block hash in the session store at this block height.
```suggestion
	// Store the current context's block hash for future height, which is currently an EndBlocker operation.
```

2024-03-21 23:31 UTC, Olshansk commented on x/proof/keeper/msg_server_submit_proof_test.go
> +	sumSize := 8
Can we retrieve this from the smt repo (no magic numbers with cross-repo dependencies)?

If not, please add TODO

2024-03-22 19:51 UTC, bryanchriswhite commented on x/proof/keeper/msg_server_submit_proof_test.go
> +				invalidRequestMetaMerkleRootBz, err := invalidRequestMetaSessionTree.Flush()
```suggestion
				invalidResponseMetaMerkleRootBz, err := invalidRsponseMetaSessionTree.Flush()
```

2024-03-22 19:53 UTC, bryanchriswhite commented on x/proof/keeper/msg_server_submit_proof_test.go
> +					invalidRequestMetaMerkleRootBz,
```suggestion
					invalidResponseMetaMerkleRootBz,
```

2024-03-22 19:53 UTC, bryanchriswhite commented on x/proof/keeper/msg_server_submit_proof_test.go
> +					invalidRequestMetaSessionTree,
```suggestion
					invalidResponseMetaSessionTree,
```

2024-03-22 20:13 UTC, bryanchriswhite commented on x/proof/keeper/msg_server_submit_proof_test.go
> +			desc: "merkle proof must validate claimed merkle root",
```suggestion
			desc: "Valid proof cannot validate claim with invalid root",
```

2024-03-22 20:16 UTC, bryanchriswhite commented on x/proof/keeper/msg_server_submit_proof_test.go
> +				// Create a valid claim.
```suggestion
				// Create a claim with the incorrect Merkle root.
```

2024-03-22 20:18 UTC, bryanchriswhite commented on x/proof/keeper/msg_server_submit_proof_test.go
> +			proofs := proofRes.GetProofs()
```suggestion
			// Expect zero proofs to have been persisted as all test cases are error cases.
			proofs := proofRes.GetProofs()
```

2024-03-22 21:48 UTC, bryanchriswhite commented
@Olshansk there are a few comments I didn't get to tend to. There are a couple of failing tests/cases as a result of resolving merge conflicts from upstream. I have to put it down for now, thanks for volunteering to get it over the finish line. 🫡

2024-03-24 00:14 UTC, Olshansk commented on x/proof/keeper/msg_server_submit_proof_test.go
> +					"error deserializing ring signature: %s",
Adding the following in the code:

```go
	{
			desc: "relay request signature is valid but signed by an incorrect application",
			newProofMsg: func(t *testing.T) *types.MsgSubmitProof {
				t.Skip("TODO_TECHDEBT(@bryanchriswhite): Implement this")
				return nil
			},
		},
```

2024-03-24 00:20 UTC, Olshansk commented on x/proof/keeper/msg_server_submit_proof_test.go
> +				t.Cleanup(func() {
The answer is yes.

2024-03-24 00:29 UTC, Olshansk commented on x/proof/keeper/msg_server_submit_proof_test.go
> +	validRelayHash := sha256.Sum256(validRelayBz)
I added `func (relay Relay) GetHash`

2024-03-24 00:29 UTC, Olshansk commented on x/proof/keeper/msg_server_submit_proof_test.go
> +	sumSize := 8
Removed the need for this.

2024-03-24 00:30 UTC, Olshansk commented on x/proof/keeper/msg_server_submit_proof_test.go
> +	supplierAddr string,
Done everywhere.

2024-03-24 00:33 UTC, Olshansk commented on x/proof/keeper/msg_server_submit_proof_test.go
> +					"session headers session start heights mismatch; expected: %d, got: %d",
Resolving because I anticipate this to naturally resurface to simply pop up once we parameterize it.

2024-03-24 01:35 UTC, Olshansk approved these changes
@bryanchriswhite Picked up where you left off and I believe I got this to the finish line.

I'm going to rebase #421 (my tokenomics PR) on top of this and start working on the integration tests.

@red-0ne @h5law PTAL at this PR again, and in particular the changes I introduced in the following commits: 
https://github.com/pokt-network/poktroll/pull/417/files/0c0ab97947932a23fc3ae43fe44af89e85c72b03..013e139db1dfbb7cb2e937091539a668c2b4027e

2024-03-25 21:19 UTC, red-0ne reviewed
Great comments all over the code! Left a few comments to the code but nothing major.

`x/proof/keeper/msg_server_submit_proof_test.go` is getting quite dense and would love to see the helper functions live in their own file (e.g. `submit_proof_test_helpers.go`)

2024-03-25 21:19 UTC, red-0ne commented on x/proof/keeper/msg_server_submit_proof_test.go
> +// TODO_DISCUSS(@red-0ne, @Olshansk): Should this logic be centralized
You can change this to a `TODO_TECHDEBT`. There's definitely room for factoring this out.

2024-03-26 01:24 UTC, Olshansk approved these changes

2024-03-26 02:10 UTC, red-0ne approved these changes
LGTM :rocket:

2024-03-26 02:18 UTC, merged