[Miner] feat: add block & supplier clients
pokt-network/poktroll pull request #42
Opened 2023-10-10 08:23 UTC by bryanchriswhite

## Summary

reviewpad:summary

## Issue

Fixes #{ISSUE_NUMBER}

[Explain the reasoning for thePR in 1-2 sentences. Consider adding a link or a screenshot.]

## Type of change

Select one or more:

- [ ] New feature, functionality or library
- [ ] Bug fix
- [ ] Code health or cleanup
- [ ] Documentation
- [ ] Other (specify)

## Testing

- [ ] **Run all unit tests**: `make test_all_unit`
- [ ] **Verify Localnet manually**: See the instructions [here](TODO: add link to instructions)

## Sanity Checklist

- [ ] I have tested my changes using the available tooling
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, updated documentation and left TODOs throughout the codebase

2023-10-13 07:16 UTC, bryanchriswhite commented on internal/testclient/common.go
> +func NewLocalnetClientCtx(t *testing.T, flagSet *pflag.FlagSet) *client.Context {
(see: https://github.com/pokt-network/poktroll/pull/59#discussion_r1357857321)

2023-10-14 22:39 UTC, h5law commented on pkg/client/supplier/proofs.go
> +	proof *smt.SparseMerkleProof,
```suggestion
	proof *smt.SparseMerkleClosestProof,
```

2023-11-03 20:49 UTC, bryanchriswhite commented on internal/testclient/testblock/client.go
> -// - ctx: The context for creating the client.
test

2023-11-03 20:51 UTC, bryanchriswhite commented on internal/testclient/testblock/client.go
I'm not sure why github is showing a diff in this file. This change was moved to #94.

2023-11-03 20:51 UTC, bryanchriswhite commented on internal/testclient/testeventsquery/client.go
I'm not sure why github is showing a diff in this file. This change was moved to #94.

2023-11-03 20:53 UTC, bryanchriswhite commented on internal/testclient/testtx/context.go
> -// NewOneTimeErrTxTimeoutTxContext creates a mock transaction context designed to simulate a specific
Changes from here down were #94. I'm not sure why github is showing this diff  here.

2023-11-03 20:54 UTC, bryanchriswhite commented on pkg/client/interface.go
> +// TxClientOption defines a function type that modifies the TxClient.
This diff was moved to #94. I'm not sure why github is showing here.

2023-11-06 19:32 UTC, Olshansk commented on internal/testclient/testblock/client.go
I'm pretty sure you know all of this, but just in case

```bash
git checkout main
git pull
# Merge with #94
git checkout feat/tx-client
git merge main
git checkout feat/supplier-client
git merge feat/tx-client
```

Open question: Why is the base of this PR `refactor/keyring-errors-helpers`?

2023-11-06 19:33 UTC, Olshansk requested changes
@bryanchriswhite You mentioned some changes are being shown / not shown which is a result of merge/base branch issues.

Going to hold off until that's resolved to avoid review overhead.

https://github.com/pokt-network/poktroll/pull/42/files#r1382188801

2023-11-06 20:20 UTC, bryanchriswhite commented on internal/testclient/testblock/client.go
#131 was isolated from #94 to reduce the diff size; however, `feat/supplier-client` depends on it:

![image](https://github.com/pokt-network/poktroll/assets/600733/c429f04f-1894-4dcd-a6a3-b50b37662419)
> Only `feat/tx-client` has merged main, dependent branches need merging (left). 
> After all branches have merged dependencies (right).

2023-11-06 20:21 UTC, bryanchriswhite commented
> @bryanchriswhite You mentioned some changes are being shown / not shown which is a result of merge/base branch issues.
> 
> Going to hold off until that's resolved to avoid review overhead.
> 
> https://github.com/pokt-network/poktroll/pull/42/files#r1382188801

This was **definitely** GitHub doing the _wrong_ thing, I triple checked. The bizarre behavior nearly coincided with some service  interruptions they experienced recently; perhaps there is a causal connection there. After poking it today, it seems to have decided to do the right thing.

2023-11-06 20:43 UTC, Olshansk approved these changes

2023-11-07 08:55 UTC, merged