[Redelegation] fix: EventRedelegation unmarshaling failure
pokt-network/poktroll pull request #435
Opened 2024-03-19 03:38 UTC by red-0ne

## Summary

Unmarshalling transaction results logic in the delegation client is outdated, making the `RelayMiner` to panic when listening for these events.

This PR uses `tx.UnmarshalTxResult` from `txClient` to unmarshal the transaction.

## Issue

When the `RelayMiner` is running and observing `EventRedelegation`s by listening to `application` transactions, if a stake application occurs, the client tries to unmarshal it with a "pre-migration" code, causing the `RelayMiner` to panic

![image](https://github.com/pokt-network/poktroll/assets/231488/7af95bfe-c916-4afe-9d16-92149c5bd07e)

## Type of change

Select one or more:

- [ ] New feature, functionality or library
- [x] Bug fix
- [ ] Code health or cleanup
- [ ] Documentation
- [ ] Other (specify)

## Testing

- [x] **Unit Tests**: `make go_develop_and_test`
- [x] **LocalNet E2E Tests**: `make test_e2e`
- [ ] **DevNet E2E Tests**: Add the `devnet-test-e2e` label to the PR. **THIS IS VERY EXPENSIVE**, so only do it after all the reviews are complete.
- [ ] **Documentation changes**: `make docusaurus_start`

## Sanity Checklist

- [x] I have tested my changes using the available tooling
- [x] I have commented my code
- [x] I have performed a self-review of my own code; both comments & source code
- [ ] I create and referenced any new tickets, if applicable
- [ ] I have left TODOs throughout the codebase, if applicable

2024-03-19 11:03 UTC, bryanchriswhite requested changes
Nice one! :ok_hand: 

IIRC correctly, when we were discussing this, we couldn't come up with a great reason not to export `cometTxEvent`. Otherwise this LGTM. :muscle:

2024-03-20 06:43 UTC, bryanchriswhite approved these changes

2024-03-21 04:10 UTC, Olshansk approved these changes

2024-03-21 04:34 UTC, h5law approved these changes
LGTM Short and sweet nice changes :)

2024-03-21 22:45 UTC, merged