[Application] Refactor app module to fetch on-chain params
pokt-network/poktroll pull request #555
Opened 2024-05-28 07:30 UTC by bryanchriswhite

## Summary

Refactor the `application` module to remove all usage of the `NumBlocksPerSession` stand-in constant, in favor of fetching the on-chain param. This involves adding the `shared` module as a dependency.

## Issue

- #517 

## Type of change

Select one or more:

- [x] New feature, functionality or library
- [ ] Bug fix
- [x] Code health or cleanup
- [ ] Documentation
- [ ] Other (specify)

## Testing

**Documentation changes** (only if making doc changes)
- [ ] `make docusaurus_start`; only needed if you make doc changes

**Local Testing** (only if making code changes)
- [x] **Unit Tests**: `make go_develop_and_test`
- [x] **LocalNet E2E Tests**: `make test_e2e`
- See [quickstart guide](https://dev.poktroll.com/developer_guide/quickstart) for instructions

**PR Testing** (only if making code changes)
- [x] **DevNet E2E Tests**: Add the `devnet-test-e2e` label to the PR.
    - **THIS IS VERY EXPENSIVE**, so only do it after all the reviews are complete.
    - Optionally run `make trigger_ci` if you want to re-trigger tests without any code changes
    - If tests fail, try re-running failed tests only using the GitHub UI as shown [here](https://github.com/pokt-network/poktroll/assets/1892194/607984e9-0615-4569-9452-4c730190c1d2)

## Sanity Checklist

- [x] I have tested my changes using the available tooling
- [x] I have commented my code
- [x] I have performed a self-review of my own code; both comments & source code
- [ ] I create and reference any new tickets, if applicable
- [x] I have left TODOs throughout the codebase, if applicable

2024-05-28 21:50 UTC, Olshansk requested changes
Will re-review the entire PR on the next round but my main feedback is:

1. s/queryHeight/blockHeight/
2. s/GetDefaultX/GetXForDefaultParams

Lmk wyt

2024-05-29 07:17 UTC, bryanchriswhite commented on x/application/types/expected_keepers.go
> +	GetSessionEndHeight(ctx context.Context, queryHeight int64) int64
I would argue that `queryHeight` has more semantically meaning than `blockHeight`, where "block" seems redundant in my view. While the word "block" by itself is ambiguous, "height" is completely unambiguous on its own. The word "query" is then adding semantic meaning by indicating that it is a free & arbitrary parameter (as opposed to having to be a session start/end height or something).

While it's not currently the case (see #543), methods like this which depend on param values SHOULD be using the (potentially historical) value of the param **at `queryHeight`**. I think this was the original reason that "query" stuck in my head.

2024-05-29 07:45 UTC, bryanchriswhite commented on x/shared/session.go
> +func GetSessionNumber(sharedParams *sharedtypes.Params, queryHeight int64) int64 {
Consolidating discussion in https://github.com/pokt-network/poktroll/pull/555#discussion_r1617787650

2024-05-30 01:43 UTC, Olshansk approved these changes
Optional comment updates

2024-05-30 01:43 UTC, Olshansk commented on x/shared/session.go
> +// Example: If NumBlocksPerSession == 4, sessions end at blocks 4, 8, 11, etc.
```suggestion
// See GetSessionEndHeight for more details.
```

2024-05-30 01:43 UTC, Olshansk commented on x/shared/session.go
> +// Example: If NumBlocksPerSession == 4, sessions start at blocks 1, 5, 9, etc.
```suggestion
// See GetSessionStartHeight for more details.
```

2024-05-30 01:43 UTC, Olshansk commented on x/shared/session.go
> +// i.e. If NubBlocksPerSession == 4, session == 1 for [1, 4], session == 2 for [5, 8], etc.
```suggestion
// See GetSessionNumber for more details.
```

2024-05-30 10:49 UTC, merged

2024-05-30 10:50 UTC, bryanchriswhite commented
:rotating_light: Do not delete branch until #556's base has changed! :rotating_light: