[On-chain] feat: add `proof_window_close_offset_blocks` as `shared` module parameter
pokt-network/poktroll pull request #570
Opened 2024-05-30 15:43 UTC by bryanchriswhite

## Summary

Adds `poktroll.shared.Params#proof_window_close_offset_blocks` to the `shared` module parameters.

## Issue

- #516

## Type of change

Select one or more:

- [x] New feature, functionality or library
- [ ] Bug fix
- [ ] Code health or cleanup
- [ ] Documentation
- [ ] Other (specify)

## Testing

**Documentation changes** (only if making doc changes)
- [ ] `make docusaurus_start`; only needed if you make doc changes

**Local Testing** (only if making code changes)
- [ ] **Unit Tests**: `make go_develop_and_test`
- [ ] **LocalNet E2E Tests**: `make test_e2e`
- See [quickstart guide](https://dev.poktroll.com/developer_guide/quickstart) for instructions

**PR Testing** (only if making code changes)
- [ ] **DevNet E2E Tests**: Add the `devnet-test-e2e` label to the PR.
    - **THIS IS VERY EXPENSIVE**, so only do it after all the reviews are complete.
    - Optionally run `make trigger_ci` if you want to re-trigger tests without any code changes
    - If tests fail, try re-running failed tests only using the GitHub UI as shown [here](https://github.com/pokt-network/poktroll/assets/1892194/607984e9-0615-4569-9452-4c730190c1d2)

## Sanity Checklist

- [ ] I have tested my changes using the available tooling
- [ ] I have commented my code
- [ ] I have performed a self-review of my own code; both comments & source code
- [ ] I create and reference any new tickets, if applicable
- [ ] I have left TODOs throughout the codebase, if applicable

2024-05-31 11:29 UTC, bryanchriswhite commented on x/shared/keeper/msg_server_update_param_test.go
> +	// Update the claim window close offset blocks param
```suggestion
	// Update the proof window close offset blocks param
```

2024-05-31 15:01 UTC, red-0ne approved these changes
LGTM

2024-05-31 15:12 UTC, red-0ne reviewed
Isn't it missing params_test and a make target to update it?

2024-05-31 21:43 UTC, Olshansk requested changes
Things we seem to have elsewhere:
1. Makefie target
2. Accompanying .json file
3. Unit test for failing update

2024-06-05 20:22 UTC, Olshansk approved these changes

2024-06-06 08:00 UTC, merged