[Refactor] Replace embedded Service with ServiceId
pokt-network/poktroll pull request #802
Opened 2024-09-07 03:10 UTC by red-0ne

## Summary

This PR replaces all embedded `Service` entries with `ServiceId`.

Most of the changes are `Service` -> `ServiceId` replacements but special attention has to be put on:
* x/session/types/session_header.go
* x/shared/helpers/service_configs.go
* x/shared/types/service.go
* x/service/types/message_add_service.go
* proto/poktroll/shared/service.proto
* proto/poktroll/session/types.proto
* proto/poktroll/session/query.proto

E2E tests pass locally.

## Issue

![image](https://github.com/user-attachments/assets/c1feb50b-89c1-4b4f-b4cb-94cfb4ec5ade)

## Type of change

Select one or more from the following:

- [ ] New feature, functionality or library
- [ ] Consensus breaking; add the `consensus-breaking` label if so. See #791 for details
- [ ] Bug fix
- [x] Code health or cleanup
- [ ] Documentation
- [ ] Other (specify)

## Testing

- [ ] **Documentation**: `make docusaurus_start`; only needed if you make doc changes
- [x] **Unit Tests**: `make go_develop_and_test`
- [x] **LocalNet E2E Tests**: `make test_e2e`
- [ ] **DevNet E2E Tests**: Add the `devnet-test-e2e` label to the PR.

## Sanity Checklist

- [x] I have tested my changes using the available tooling
- [ ] I have commented my code
- [x] I have performed a self-review of my own code; both comments & source code
- [ ] I create and reference any new tickets, if applicable
- [ ] I have left TODOs throughout the codebase, if applicable

2024-09-09 22:47 UTC, Olshansk approved these changes
That was much easier than expected, eh?

2024-09-09 22:47 UTC, Olshansk commented on x/shared/types/service.go
> +	// Should we revisit all uint64 and convert them to BigInts?
lol

2024-09-10 09:29 UTC, bryanchriswhite reviewed
:ok_hand: Nice one @red-0ne! :sunglasses: 

It's interesting to see the effect this change has on the imports. I wonder if it has any effect on the module dependency tree. :thinking: It seems like we still need the `shared` module though as it currently contains the `Supplier` protobuf type as well.

2024-09-10 09:51 UTC, bryanchriswhite requested changes

2024-09-10 09:51 UTC, bryanchriswhite commented on x/proof/types/message_submit_proof_test.go
> +				return ErrProofInvalidSessionHeader.Wrapf("invalid session header: %s", serviceError)
```suggestion
				return ErrProofInvalidSessionHeader.Wrapf("%s", serviceError)
```

2024-09-10 09:51 UTC, bryanchriswhite commented on x/session/keeper/session_hydrator.go
> +	if !sharedtypes.IsValidServiceId(sh.sessionHeader.ServiceId) {
Nice reversal :joy::ok_hand: :dizzy:

2024-09-10 09:51 UTC, bryanchriswhite commented on x/session/types/errors.go
> +	ErrSessionServiceNotFound        = sdkerrors.Register(ModuleName, 1110, "service not found")
This doesn't seem to be used anywhere (according to my IDE). Is it mistaken?

2024-09-10 09:51 UTC, bryanchriswhite commented on x/shared/types/service.go
> +	ComputeUnitsPerRelayMax uint64 = 2 ^ 16
```suggestion
	ComputeUnitsPerRelayMax uint64 = 2 ^ 16  // 65536
```

2024-09-10 14:59 UTC, bryanchriswhite approved these changes
Preemptively approving. :+1: 

Just a few more suggestions regarding error messages; otherwise, LGTM. :ship:

2024-09-11 02:51 UTC, Olshansk commented
Let's merge this in!

2024-09-11 04:14 UTC, merged