[DifficultyHash] Prepare for difficulty multiplier usage
pokt-network/poktroll pull request #836
Opened 2024-09-24 23:03 UTC by red-0ne

## Summary

This PR prepares for claimed amount calculation to use the `RelayDifficultyMultiplier`.
* It removes the `RelayDifficultyTargetHash` `proof` param.
* Replace `prooftypes.DefaultRelayDifficultyTargetHash` occurrences with `protocol.BaseRelayDifficultyHashBz`.
* Moves the `RleayMiningDifficulty` logic to the `service` module due to cyclic dependencies.
* Rename `num_compute_units` to `num_claimed_compute_units` and add `num_estimated_compute_units` and `claimed_amount_upokt`
* Remove the no longer used tokenomics querier to retrieve a service difficulty target hash.

The PR is only renaming and moving of files most (~13200LOC) changes are auto-generated code.

## Type of change

Select one or more from the following:

- [ ] New feature, functionality or library
- [x] Consensus breaking; add the `consensus-breaking` label if so. See #791 for details
- [ ] Bug fix
- [x] Code health or cleanup
- [ ] Documentation
- [ ] Other (specify)

## Testing

- [ ] **Documentation**: `make docusaurus_start`; only needed if you make doc changes
- [x] **Unit Tests**: `make go_develop_and_test`
- [x] **LocalNet E2E Tests**: `make test_e2e`
- [ ] **DevNet E2E Tests**: Add the `devnet-test-e2e` label to the PR.

## Sanity Checklist

- [x] I have tested my changes using the available tooling
- [x] I have commented my code
- [x] I have performed a self-review of my own code; both comments & source code
- [ ] I create and reference any new tickets, if applicable
- [ ] I have left TODOs throughout the codebase, if applicable

2024-09-30 11:01 UTC, bryanchriswhite reviewed
![image](https://github.com/user-attachments/assets/41c7d23e-433b-4669-b2bf-96ffe95137c3)

2024-09-30 20:21 UTC, Olshansk requested changes
Will TAL after merged with main

2024-10-07 17:55 UTC, bryanchriswhite reviewed
![image](https://github.com/user-attachments/assets/c77e70ad-76d4-4aa8-9b59-00433ef71e09)

2024-10-08 08:14 UTC, bryanchriswhite approved these changes
Preemptively approving! :raised_hands: 

Just a couple questions and small suggestions - otherwise this LGTM! :ship:

2024-10-08 08:14 UTC, bryanchriswhite commented on x/proof/types/message_update_param_test.go
> +				Name:      "WRONG_proof_missing_penalty",
For consistency:

```suggestion
				Name:      "non_existent",
```

See [the updated params guide](https://github.com/pokt-network/poktroll/blob/5c995f12ea6957d57c7350f9186ff15bddcc971c/docusaurus/docs/develop/developer_guide/adding_params.md#52-parameter-update-tests):

![image](https://github.com/user-attachments/assets/bbf0744e-3e56-4da8-8afa-2ed8088ad324)

2024-10-08 08:14 UTC, bryanchriswhite commented on x/service/types/genesis_test.go
> +			desc: "invalid - duplicated relayMiningDifficulty",
:ok_hand:

2024-10-08 08:14 UTC, bryanchriswhite commented on x/service/types/genesis.go
> +	}
Wdyt about extracting these to methods (e.g. `#validateServiceList()` & `#validateRelayMiningDifficultyList()`)?

2024-10-09 23:53 UTC, red-0ne commented on testutil/integration/app.go
> +		servicetypes.ModuleName:    {authtypes.Minter, authtypes.Burner},
Good catch! It was unnecessary.

2024-10-10 03:08 UTC, merged