[Workflow] Enforce `TODO_UPNEXT` comments to have an associated username
pokt-network/poktroll pull request #896
Opened 2024-10-28 19:19 UTC by Olshansk

## Summary

Improve process for `TODO_UPNEXT`

Goal is to block PRs on this: `TODO_UPNEXT: <do something>`
Allow PRs on this: `TODO_UPNEXT(@olshansk): <do something>`

## Issue

NA

## Type of change

Select one or more from the following:

- [x] New feature, functionality or library
- [ ] Consensus breaking; add the `consensus-breaking` label if so. See #791 for details
- [ ] Bug fix
- [ ] Code health or cleanup
- [ ] Documentation
- [ ] Other (specify)

## Testing

2024-10-28 19:27 UTC, Olshansk commented
@okdas Is there easy way to test this without merging it in?

2024-10-28 19:46 UTC, okdas requested changes
> @okdas Is there easy way to test this without merging it in?

Yes - this PR can be used for testing. Just add `TODO_UPNEXT:` to any file.

2024-10-28 19:46 UTC, okdas commented on .github/workflows/reviewdog.yml
> +          pattern: TODO_UPNEXT:
```suggestion
          pattern: "TODO_UPNEXT:"
```
This line breaks the config: https://github.com/pokt-network/poktroll/actions/runs/11561203740/workflow

With this suggestion committed, I think this should work.

2024-11-05 12:29 UTC, bryanchriswhite approved these changes
Very cool. :sunglasses: 

It would be nice if we could modify the comment contents to explain WHY it's complaining and what the author needs to change (i.e. add attribution). Perhaps it's out of scope but I'm wondering if that could be trivially possible via a different "reporter" or something?

(cc @okdas)

2024-11-05 15:35 UTC, merged

2024-11-05 15:35 UTC, Olshansk commented
CCing @okdas and snoozing this email until next week.