[Tokenomics] feat: add `dao_reward_address` param to tokenomics module
pokt-network/poktroll pull request #922
Opened 2024-11-13 20:24 UTC by bryanchriswhite

## Summary

Add `dao_reward_address` param to the tokenomics module.

## Issue

- `TODO_BETA`

## Type of change

Select one or more from the following:

- [ ] New feature, functionality or library
- [ ] Consensus breaking; add the `consensus-breaking` label if so. See #791 for details
- [ ] Bug fix
- [ ] Code health or cleanup
- [ ] Documentation
- [ ] Other (specify)

## Testing

- [ ] **Documentation**: `make docusaurus_start`; only needed if you make doc changes
- [ ] **Unit Tests**: `make go_develop_and_test`
- [ ] **LocalNet E2E Tests**: `make test_e2e`
- [ ] **DevNet E2E Tests**: Add the `devnet-test-e2e` label to the PR.

## Sanity Checklist

- [ ] I have tested my changes using the available tooling
- [ ] I have commented my code
- [ ] I have performed a self-review of my own code; both comments & source code
- [ ] I create and reference any new tickets, if applicable
- [ ] I have left TODOs throughout the codebase, if applicable

2024-11-13 20:27 UTC, bryanchriswhite commented on config.yml
> +        dao_reward_address: "pokt1eeeksh2tvkh7wzmfrljnhw4wrhs55lcuvmekkw"
```suggestion
        # The dao reward address SHOULD match that of the "pnf" below (i.e. `make poktrolld_addr ACC_NAME=pnf`).
        # This is the address that will receive the dao/foundation rewards during claim settlement (global mint TLM).
        dao_reward_address: "pokt1eeeksh2tvkh7wzmfrljnhw4wrhs55lcuvmekkw"
```

2024-11-15 20:28 UTC, Olshansk requested changes

2024-11-15 20:28 UTC, Olshansk commented on config.yml
> +        # The dao reward address SHOULD match that of the "pnf" below (i.e. `make poktrolld_addr ACC_NAME=pnf`).
Can you add a `TODO_MAINNET(@Olshansk): Consolidate the usage of DAO/PNF throughout the configs & codebase`

2024-11-15 20:28 UTC, Olshansk commented on x/tokenomics/types/params.go
> +	// DEV_NOTE: Empty string is valid if mint_allocation_dao is 0.
Hmmm, why?

Any chance we can just prevent this from ever being zero altogether and avoid bugs or special/edge cases?

2024-11-15 20:28 UTC, Olshansk commented on x/tokenomics/types/params.go
> +// empty string so long as the mint_allocation_dao param is not 0.
`// empty string so long as the mint_allocation_dao param is not 0.`

I understand WHY you did this, but I'd rather keep it simpler. Less prone to bugs.

2024-11-15 20:28 UTC, Olshansk commented on x/tokenomics/types/message_update_param.go
> +// TODO_TECHDEBT:
```suggestion
// TODO_TECHDEBT(@bryanchriswhite):
```

2024-11-15 20:28 UTC, Olshansk commented on x/tokenomics/types/message_update_param.go
> +// 2. Refactor other module mesagese_upddate_param.go files to use this.
```suggestion
// 2. Refactor other module message_update_param.go files to use this.
```

2024-11-18 16:55 UTC, merged