[Code Health] fix: tokenomics module gRPC return errors
pokt-network/poktroll pull request #963
Opened 2024-11-25 15:39 UTC by bryanchriswhite

## Summary

Ensure all supplier message and query handlers return gRPC status errors.

## Issue

- #{860

## Type of change

Select one or more from the following:

- [ ] New feature, functionality or library
- [ ] Consensus breaking; add the `consensus-breaking` label if so. See #791 for details
- [ ] Bug fix
- [x] Code health or cleanup
- [ ] Documentation
- [ ] Other (specify)

## Testing

- [ ] **Documentation**: `make docusaurus_start`; only needed if you make doc changes
- [x] **Unit Tests**: `make go_develop_and_test`
- [ ] **LocalNet E2E Tests**: `make test_e2e`
- [x] **DevNet E2E Tests**: Add the `devnet-test-e2e` label to the PR.

## Sanity Checklist

- [x] I have tested my changes using the available tooling
- [ ] I have commented my code
- [x] I have performed a self-review of my own code; both comments & source code
- [ ] I create and reference any new tickets, if applicable
- [ ] I have left TODOs throughout the codebase, if applicable

2024-11-27 16:05 UTC, red-0ne requested changes
Tiny change request.

2024-11-27 16:05 UTC, red-0ne commented on x/tokenomics/keeper/msg_update_params.go
> +		err = status.Error(codes.Internal, err.Error())
```suggestion
```

Also, shouldn't we log here?

2024-12-02 08:31 UTC, bryanchriswhite commented on x/tokenomics/keeper/msg_update_params.go
> +		err = status.Error(codes.Internal, err.Error())
Nice catch! Ty! :pray:

2024-12-02 12:38 UTC, red-0ne approved these changes

2024-12-02 13:15 UTC, merged